#%RAML 1.0 NamedExample
value:
  -
    name: EMCA
    type: business
    address: "1 Main St,Los Angeles,CA,92000,USA"
    air_miles: 500
  - 
    name: John Doe
    type: personal
    address: "1 Main St,Los Angeles,CA,92000,USA"
    air_miles: 2600