#%RAML 1.0 NamedExample
value:
  -
    id: 1
    name: ACME
    type: business
    address: "1 Main St,Los Angeles,CA,92000,USA"
    air_miles: 5000
    created_at: 2020-09-21T12:00:00Z
  - 
    id: 2
    name: Jane Doe
    type: personal
    address: "1 Main St,Los Angeles,CA,92000,USA"
    air_miles: 50000
    created_at: 2010-01-01T00:00:00Z